"""empty message

Revision ID: 14ef0198fff0
Revises: e4cc4ee7f3bd
Create Date: 2026-05-21 12:33:08.670136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ef0198fff0'
down_revision: Union[str, Sequence[str], None] = 'e4cc4ee7f3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('sha', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('technical', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('process', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('risks', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('conventional_commits', sa.Boolean(), nullable=False))
    op.add_column('commits', sa.Column('author', sa.String(), nullable=False))
    op.alter_column('commits', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'commits', ['sha'])
    op.drop_column('commits', 'id')
    op.drop_index(op.f('ix_projects_repo_full_name'), table_name='projects')
    op.create_index(op.f('ix_projects_repo_full_name'), 'projects', ['repo_full_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_repo_full_name'), table_name='projects')
    op.create_index(op.f('ix_projects_repo_full_name'), 'projects', ['repo_full_name'], unique=False)
    op.add_column('commits', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'commits', type_='unique')
    op.alter_column('commits', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('commits', 'author')
    op.drop_column('commits', 'conventional_commits')
    op.drop_column('commits', 'risks')
    op.drop_column('commits', 'process')
    op.drop_column('commits', 'technical')
    op.drop_column('commits', 'sha')
    # ### end Alembic commands ###
