"""empty message

Revision ID: 0bfa8dd3045e
Revises: ec36b5d978ca
Create Date: 2026-05-14 12:55:41.663187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfa8dd3045e'
down_revision: Union[str, Sequence[str], None] = 'ec36b5d978ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.BIGINT(), nullable=False))
    op.add_column('users', sa.Column('github_token', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_column('users', 'github_token')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
