"""empty message

Revision ID: 1e72c7378d53
Revises: 1773e65a5d47
Create Date: 2026-05-23 12:13:04.831350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e72c7378d53'
down_revision: Union[str, Sequence[str], None] = '1773e65a5d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yaMatTvoyuEbal')
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=63),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=63),
               existing_nullable=False)
    op.create_table('yaMatTvoyuEbal',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('title', name=op.f('yaMatTvoyuEbal_pkey'))
    )
    # ### end Alembic commands ###
