"""empty message

Revision ID: e4cc4ee7f3bd
Revises: b02aa443d67c
Create Date: 2026-05-16 10:13:24.377583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cc4ee7f3bd'
down_revision: Union[str, Sequence[str], None] = 'b02aa443d67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repo_full_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('webhook_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('webhook_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_repo_full_name'), 'projects', ['repo_full_name'], unique=False)
    op.create_index(op.f('ix_projects_webhook_id'), 'projects', ['webhook_id'], unique=True)
    op.create_unique_constraint(None, 'projects', ['webhook_secret'])
    op.drop_column('projects', 'repo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_webhook_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_repo_full_name'), table_name='projects')
    op.drop_column('projects', 'webhook_secret')
    op.drop_column('projects', 'webhook_id')
    op.drop_column('projects', 'repo_full_name')
    # ### end Alembic commands ###
